# syntax=docker/dockerfile:1.7

# ---- build stage ---------------------------------------------------------
FROM node:20-alpine AS builder
WORKDIR /app

# Vite inlines VITE_* values at build time, so the Firebase/VAPID config has
# to be present here (not at container runtime). docker-compose passes these
# in via `build.args` from the host's .env file.
ARG VITE_FIREBASE_API_KEY=""
ARG VITE_FIREBASE_AUTH_DOMAIN=""
ARG VITE_FIREBASE_PROJECT_ID=""
ARG VITE_FIREBASE_STORAGE_BUCKET=""
ARG VITE_FIREBASE_MESSAGING_SENDER_ID=""
ARG VITE_FIREBASE_APP_ID=""
ARG VITE_FIREBASE_VAPID_KEY=""
ARG VITE_LOCAL_MODE=""
ARG VITE_UMAMI_WEBSITE_ID=""
ARG VITE_UMAMI_SCRIPT_URL=""
ARG VITE_LEGAL_COMPANY=""
ARG VITE_LEGAL_ADDRESS_STREET=""
ARG VITE_LEGAL_ADDRESS_CITY=""
ARG VITE_LEGAL_ADDRESS_COUNTRY=""
ARG VITE_LEGAL_EMAIL=""
ARG VITE_LEGAL_MANAGING_DIRECTOR=""
ARG VITE_LEGAL_REGISTER_COURT=""
ARG VITE_LEGAL_REGISTER_NUMBER=""
ARG VITE_LEGAL_VAT_ID=""
ARG VITE_LEGAL_SUPERVISORY_AUTHORITY=""
ARG VITE_LEGAL_SUPERVISORY_ADDRESS=""
ARG VITE_LEGAL_SUPERVISORY_URL=""

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY \
    VITE_LOCAL_MODE=$VITE_LOCAL_MODE \
    VITE_UMAMI_WEBSITE_ID=$VITE_UMAMI_WEBSITE_ID \
    VITE_UMAMI_SCRIPT_URL=$VITE_UMAMI_SCRIPT_URL \
    VITE_LEGAL_COMPANY=$VITE_LEGAL_COMPANY \
    VITE_LEGAL_ADDRESS_STREET=$VITE_LEGAL_ADDRESS_STREET \
    VITE_LEGAL_ADDRESS_CITY=$VITE_LEGAL_ADDRESS_CITY \
    VITE_LEGAL_ADDRESS_COUNTRY=$VITE_LEGAL_ADDRESS_COUNTRY \
    VITE_LEGAL_EMAIL=$VITE_LEGAL_EMAIL \
    VITE_LEGAL_MANAGING_DIRECTOR=$VITE_LEGAL_MANAGING_DIRECTOR \
    VITE_LEGAL_REGISTER_COURT=$VITE_LEGAL_REGISTER_COURT \
    VITE_LEGAL_REGISTER_NUMBER=$VITE_LEGAL_REGISTER_NUMBER \
    VITE_LEGAL_VAT_ID=$VITE_LEGAL_VAT_ID \
    VITE_LEGAL_SUPERVISORY_AUTHORITY=$VITE_LEGAL_SUPERVISORY_AUTHORITY \
    VITE_LEGAL_SUPERVISORY_ADDRESS=$VITE_LEGAL_SUPERVISORY_ADDRESS \
    VITE_LEGAL_SUPERVISORY_URL=$VITE_LEGAL_SUPERVISORY_URL

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# ---- runtime stage -------------------------------------------------------
FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget -qO- http://127.0.0.1:8080/healthz >/dev/null 2>&1 || exit 1
