import { useCallback, useEffect, useRef } from "react";
import { useSettings } from "@/lib/settings";
import { findVoiceProfile } from "@/lib/voiceProfiles";

// Pre-rendered voice prompts.
//
// Every prompt comes from a fixed vocabulary, so we ship MP3 clips and play
// them with HTMLAudioElement. Two channels:
//
//   - **Main**: the action prompt ("Breathe in", "Hold", ...) at full
//     voiceVolume.
//   - **Counts**: number clips ("One"..."Fifteen") at 60% volume, scheduled
//     to fire during the phase wind-down without overlapping the action.
//
// Files live at public/voice/{profileId}/{slug}.mp3. Generated by
// scripts/generate-voice.sh (edge-tts; pip install edge-tts).

const PROMPT_SLUGS: Record<string, string> = {
  "Breathe in": "breathe-in",
  "Breathe out": "breathe-out",
  Hold: "hold",
  "Top up": "top-up",
  "Long exhale": "long-exhale",
  In: "in",
  Out: "out",
  "Empty the lungs": "empty-the-lungs",
  "Inhale left": "inhale-left",
  "Exhale right": "exhale-right",
  "Inhale right": "inhale-right",
  "Exhale left": "exhale-left",
  Settle: "settle",
  Rest: "rest",
};

const PREVIEW_SLUG = "preview";
const MAX_COUNT = 15;

// Counts have a per-N whisper filter + volume gradient baked in at generate
// time (see whisper_filter_for_count in scripts/generate-voice.sh): count-15
// at ~0.55 down to count-1 at ~0.18, so they hush as the phase winds down.
// The JS-side ratio stays at 1.0 — the file is the source of truth.
const COUNT_VOLUME_RATIO = 1.0;

/** Don't bother counting on phases shorter than this. */
const COUNT_MIN_PHASE_MS = 3000;

/** Minimum silence between the end of the action prompt and the first count.
 *  Keeps the first count from sounding crowded by the prompt. The hard work
 *  of dropping "rushed" counts is mostly done by the overlap check below —
 *  this gap just provides a small grace zone right after the prompt. */
const POST_ACTION_GAP_MS = 600;

/** Allowed overhang when a count clip's tail extends past the next count's
 *  start. Set to zero: if count-N is still talking when count-(N-1) is meant
 *  to fire, drop count-N entirely. Count clips happen to run ~0.9–1.13 s
 *  (longer than the 1 s grid), so without this rule the higher counts overlap
 *  by ~30–130 ms and the announcer sounds like they're racing the clock. */
const COUNT_OVERLAP_TOLERANCE_MS = 0;

/** Fallback if we don't yet have the measured duration for a clip. */
const FALLBACK_ACTION_DURATION_MS = 1200;
/** Fallback count-clip duration used until loadedmetadata resolves. */
const FALLBACK_COUNT_DURATION_MS = 1000;

const clipUrl = (profileId: string, slug: string): string =>
  `/voice/${profileId}/${slug}.mp3`;

export function useSpeech() {
  const { settings } = useSettings();

  // The action prompt plays on one shared <audio> element (its src swaps
  // between prompts; that's fine because action prompts are seconds apart).
  const mainAudioRef = useRef<HTMLAudioElement | null>(null);
  // Count clips each get their own preloaded <audio> element. Otherwise a
  // single shared element has to swap .src between count-3 / count-2 /
  // count-1 at one-second intervals, and the resulting load race can clip
  // the start of the third clip. With one element per count, .play() acts
  // on a fully-loaded element — instant, deterministic.
  const countAudiosRef = useRef<HTMLAudioElement[]>([]);

  if (mainAudioRef.current === null && typeof window !== "undefined") {
    mainAudioRef.current = new Audio();
    mainAudioRef.current.preload = "auto";
  }

  // Pending setTimeout IDs for scheduled count clips; cleared on cancel/new speak.
  const pendingTimeoutsRef = useRef<number[]>([]);

  // Measured action-clip durations (ms), keyed by slug, for the active profile.
  const actionDurationsRef = useRef<Map<string, number>>(new Map());
  // Measured count-clip durations (ms), keyed by N (1..MAX_COUNT). Used so we
  // can skip a count whose tail would crowd the next one on a 1-s grid.
  const countDurationsRef = useRef<Map<number, number>>(new Map());

  // Volumes — kept in sync with settings without re-creating audio elements.
  useEffect(() => {
    const v = Math.max(0, Math.min(1, settings.voiceVolume));
    if (mainAudioRef.current) mainAudioRef.current.volume = v;
    for (const el of countAudiosRef.current) {
      el.volume = v * COUNT_VOLUME_RATIO;
    }
  }, [settings.voiceVolume]);

  // (Re)build the per-count audio pool + preload action-clip durations
  // whenever the voice profile changes.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const profile = findVoiceProfile(settings.voiceProfile);

    // Action-clip durations (for countdown scheduling). Metadata-only fetch.
    actionDurationsRef.current = new Map();
    for (const slug of Object.values(PROMPT_SLUGS)) {
      const a = new Audio(clipUrl(profile.id, slug));
      a.preload = "metadata";
      a.addEventListener(
        "loadedmetadata",
        () => {
          if (!Number.isFinite(a.duration)) return;
          actionDurationsRef.current.set(slug, a.duration * 1000);
        },
        { once: true },
      );
    }

    // Count-clip pool. One Audio element per count number, preloaded. We also
    // capture each clip's duration once it's known so the scheduler can avoid
    // ones whose tail would crowd the next count.
    countDurationsRef.current = new Map();
    const vol =
      Math.max(0, Math.min(1, settings.voiceVolume)) * COUNT_VOLUME_RATIO;
    countAudiosRef.current = Array.from({ length: MAX_COUNT }, (_, i) => {
      const a = new Audio(clipUrl(profile.id, `count-${i + 1}`));
      a.preload = "auto";
      a.volume = vol;
      a.addEventListener(
        "loadedmetadata",
        () => {
          if (!Number.isFinite(a.duration)) return;
          countDurationsRef.current.set(i + 1, a.duration * 1000);
        },
        { once: true },
      );
      return a;
    });
  }, [settings.voiceProfile, settings.voiceVolume]);

  const clearScheduled = useCallback(() => {
    for (const id of pendingTimeoutsRef.current) clearTimeout(id);
    pendingTimeoutsRef.current = [];
  }, []);

  const playOn = useCallback(
    (el: HTMLAudioElement | null, src: string) => {
      if (!el) return;
      el.pause();
      el.currentTime = 0;
      if (!el.src.endsWith(src)) el.src = src;
      void el.play().catch(() => {});
    },
    [],
  );

  const speak = useCallback(
    (text: string, durationMs?: number) => {
      // A new prompt always cancels any pending counts from the previous phase.
      clearScheduled();

      if (!settings.voiceEnabled) return;
      const slug = PROMPT_SLUGS[text];
      if (!slug) return;

      const profile = findVoiceProfile(settings.voiceProfile);
      playOn(mainAudioRef.current, clipUrl(profile.id, slug));

      if (!settings.countdownEnabled) return;
      if (!durationMs || durationMs < COUNT_MIN_PHASE_MS) return;

      const actionMs =
        actionDurationsRef.current.get(slug) ?? FALLBACK_ACTION_DURATION_MS;
      const earliestCountStartMs = actionMs + POST_ACTION_GAP_MS;
      const maxCount = Math.min(
        MAX_COUNT,
        Math.floor(durationMs / 1000) - 1,
      );

      // Plan first, schedule second. For each remaining-second count n,
      // fire at (durationMs - n*1000) ms after phase start. Skip ones that
      // would either land during the action prompt or run too far past the
      // slot of the next count — that's what produced the "rushed N" feeling
      // on phases like belly-breathing's 6 s exhale (count clips are ~1 s
      // but the gap to N-1 is exactly 1 s, so the higher counts overlap).
      // The last count (n=1) skips the overlap check — there's no next count
      // to crowd, and the trailing edge against the next phase's action
      // prompt is intentional (acts as a handoff).
      const planned: { n: number; fireAt: number }[] = [];
      for (let n = maxCount; n >= 1; n--) {
        const fireAt = durationMs - n * 1000;
        if (fireAt < earliestCountStartMs) continue;
        if (fireAt >= durationMs) continue;
        if (n > 1) {
          const clipMs =
            countDurationsRef.current.get(n) ?? FALLBACK_COUNT_DURATION_MS;
          const nextEventMs = durationMs - (n - 1) * 1000;
          if (fireAt + clipMs > nextEventMs + COUNT_OVERLAP_TOLERANCE_MS)
            continue;
        }
        planned.push({ n, fireAt });
      }

      // A lone count (just "one" at the end) reads as a random ping rather
      // than a countdown — skip the whole thing if fewer than two would fire.
      if (planned.length < 2) return;

      for (const { n, fireAt } of planned) {
        const handle = window.setTimeout(() => {
          const el = countAudiosRef.current[n - 1];
          if (!el) return;
          el.pause();
          el.currentTime = 0;
          void el.play().catch(() => {});
        }, fireAt);
        pendingTimeoutsRef.current.push(handle);
      }
    },
    [
      settings.voiceEnabled,
      settings.voiceProfile,
      settings.countdownEnabled,
      playOn,
      clearScheduled,
    ],
  );

  const cancel = useCallback(() => {
    clearScheduled();
    const m = mainAudioRef.current;
    if (m) {
      m.pause();
      m.currentTime = 0;
    }
    for (const el of countAudiosRef.current) {
      el.pause();
      el.currentTime = 0;
    }
  }, [clearScheduled]);

  const preview = useCallback(
    (profileId?: string) => {
      const profile = findVoiceProfile(profileId ?? settings.voiceProfile);
      playOn(mainAudioRef.current, clipUrl(profile.id, PREVIEW_SLUG));
    },
    [settings.voiceProfile, playOn],
  );

  return { speak, cancel, preview };
}
