import { useCallback, useEffect, useRef } from "react";
import { useSettings } from "@/lib/settings";
import { findVoiceProfile } from "@/lib/voiceProfiles";

// Pre-rendered voice prompts.
//
// Every prompt comes from a fixed vocabulary, so we ship MP3 clips and play
// them with HTMLAudioElement. Two channels:
//
//   - **Main**: the action prompt ("Breathe in", "Hold", ...) at full
//     voiceVolume.
//   - **Counts**: number clips ("One"..."Fifteen") at 60% volume, scheduled
//     to fire during the phase wind-down without overlapping the action.
//
// Files live at public/voice/{profileId}/{slug}.mp3. Generated by
// scripts/generate-voice.sh (edge-tts; pip install edge-tts).

const PROMPT_SLUGS: Record<string, string> = {
  "Breathe in": "breathe-in",
  "Breathe out": "breathe-out",
  Hold: "hold",
  "Top up": "top-up",
  "Long exhale": "long-exhale",
  In: "in",
  Out: "out",
  "Empty the lungs": "empty-the-lungs",
  "Inhale left": "inhale-left",
  "Exhale right": "exhale-right",
  "Inhale right": "inhale-right",
  "Exhale left": "exhale-left",
  Settle: "settle",
  Rest: "rest",
};

const PREVIEW_SLUG = "preview";
const MAX_COUNT = 15;
const COUNT_VOLUME_RATIO = 0.6; // counts play at 60% of voiceVolume

/** Don't bother counting on phases shorter than this. */
const COUNT_MIN_PHASE_MS = 3000;

/** Safety margin between the end of the action prompt and the first count. */
const POST_ACTION_GAP_MS = 250;

/** Fallback if we don't yet have the measured duration for a clip. */
const FALLBACK_ACTION_DURATION_MS = 1500;

const clipUrl = (profileId: string, slug: string): string =>
  `/voice/${profileId}/${slug}.mp3`;

export function useSpeech() {
  const { settings } = useSettings();

  // Two parallel <audio> elements — action and count run on separate channels
  // because counts may need to start before action finishes decaying.
  const mainAudioRef = useRef<HTMLAudioElement | null>(null);
  const countAudioRef = useRef<HTMLAudioElement | null>(null);
  if (mainAudioRef.current === null && typeof window !== "undefined") {
    mainAudioRef.current = new Audio();
    mainAudioRef.current.preload = "auto";
    countAudioRef.current = new Audio();
    countAudioRef.current.preload = "auto";
  }

  // Pending setTimeout IDs for scheduled count clips; cleared on cancel/new speak.
  const pendingTimeoutsRef = useRef<number[]>([]);

  // Measured action-clip durations (ms), keyed by slug, for the active profile.
  const actionDurationsRef = useRef<Map<string, number>>(new Map());

  // Volumes — kept in sync with settings without re-creating audio elements.
  useEffect(() => {
    const v = Math.max(0, Math.min(1, settings.voiceVolume));
    if (mainAudioRef.current) mainAudioRef.current.volume = v;
    if (countAudioRef.current) countAudioRef.current.volume = v * COUNT_VOLUME_RATIO;
  }, [settings.voiceVolume]);

  // Preload action-clip durations whenever the voice profile changes. Using
  // `loadedmetadata` is enough — we never need the audio bytes here, just
  // the duration so countdown scheduling can leave room for the action.
  useEffect(() => {
    const profile = findVoiceProfile(settings.voiceProfile);
    actionDurationsRef.current = new Map();
    const slugs = Object.values(PROMPT_SLUGS);
    for (const slug of slugs) {
      const a = new Audio(clipUrl(profile.id, slug));
      a.preload = "metadata";
      const onLoaded = () => {
        if (!Number.isFinite(a.duration)) return;
        actionDurationsRef.current.set(slug, a.duration * 1000);
      };
      a.addEventListener("loadedmetadata", onLoaded, { once: true });
    }
  }, [settings.voiceProfile]);

  const clearScheduled = useCallback(() => {
    for (const id of pendingTimeoutsRef.current) clearTimeout(id);
    pendingTimeoutsRef.current = [];
  }, []);

  const playOn = useCallback(
    (el: HTMLAudioElement | null, src: string) => {
      if (!el) return;
      el.pause();
      el.currentTime = 0;
      if (!el.src.endsWith(src)) el.src = src;
      void el.play().catch(() => {});
    },
    [],
  );

  const speak = useCallback(
    (text: string, durationMs?: number) => {
      // A new prompt always cancels any pending counts from the previous phase.
      clearScheduled();

      if (!settings.voiceEnabled) return;
      const slug = PROMPT_SLUGS[text];
      if (!slug) return;

      const profile = findVoiceProfile(settings.voiceProfile);
      playOn(mainAudioRef.current, clipUrl(profile.id, slug));

      if (!durationMs || durationMs < COUNT_MIN_PHASE_MS) return;

      const actionMs =
        actionDurationsRef.current.get(slug) ?? FALLBACK_ACTION_DURATION_MS;
      const earliestCountStartMs = actionMs + POST_ACTION_GAP_MS;
      const maxCount = Math.min(
        MAX_COUNT,
        Math.floor(durationMs / 1000) - 1,
      );

      // For each remaining-second count n, fire at (durationMs - n*1000) ms
      // after phase start. Skip any that would land during the action prompt.
      for (let n = maxCount; n >= 1; n--) {
        const fireAt = durationMs - n * 1000;
        if (fireAt < earliestCountStartMs) continue;
        if (fireAt >= durationMs) continue;
        const handle = window.setTimeout(() => {
          playOn(countAudioRef.current, clipUrl(profile.id, `count-${n}`));
        }, fireAt);
        pendingTimeoutsRef.current.push(handle);
      }
    },
    [settings.voiceEnabled, settings.voiceProfile, playOn, clearScheduled],
  );

  const cancel = useCallback(() => {
    clearScheduled();
    const m = mainAudioRef.current;
    const c = countAudioRef.current;
    if (m) {
      m.pause();
      m.currentTime = 0;
    }
    if (c) {
      c.pause();
      c.currentTime = 0;
    }
  }, [clearScheduled]);

  const preview = useCallback(
    (profileId?: string) => {
      const profile = findVoiceProfile(profileId ?? settings.voiceProfile);
      playOn(mainAudioRef.current, clipUrl(profile.id, PREVIEW_SLUG));
    },
    [settings.voiceProfile, playOn],
  );

  return { speak, cancel, preview };
}
